#----------------------
#Makefile 
#(c) H.Buchmann FHNW 2015
#we are in src 
# TODO change so that all works in work
#see http://www.tldp.org/LDP/lkmpg/2.6/html/x181.html
#----------------------
#KERNEL=/lib/modules/4.14.9-1-ARCH/build/
#KERNEL=${PWD}/../../5-kernel/build
#-------------------- add here your modules
obj-m += gpio-0.o gpio-1.o gpio-2.o gpio-3.o gpio-4.o gpio-5.o gpio-6.o gpio-7.o


