#---------------------------
#Makefile
#(c) H.Buchmann FHNW 2015
#---------------------------
PREFIX=arm-linux-gnueabihf-
TC=../tc/bin/${PREFIX}
SYSROOT=../../17-build/target-root
CC=${TC}gcc --sysroot=${SYSROOT}
VPATH=../src
led-demo:	led-demo.c
