#!/bin/bash

mountpoint=${PWD}/..

read -p 'Hostname: ' host
printf "Checking avaliablity of ${host}\n"

if ping -c 1 ${host} > /dev/null; then
	read -p 'Host avaliable, username: ' username
	printf 'Mounting Host\n'
	sshfs ${username}@${host}:/ ${mountpoint}/target-root
	sshfs ${username}@${host}:/home/debian/Desktop/work ${mountpoint}/work
	printf 'Mounted succesfully, login (yes/no)? ' 
	read input
	if [ ${input} = "yes" ] || [ ${input} = "y" ]; then
		echo "Logging in to ${host}"
		ssh ${username}@${host}
	else 
		:
	fi
else
	printf 'Host not reachable!\n'
fi
printf "Done!\n"





