/* confdefs.h.  */
#define PACKAGE_NAME "OpenSSH"
#define PACKAGE_TARNAME "openssh"
#define PACKAGE_VERSION "Portable"
#define PACKAGE_STRING "OpenSSH Portable"
#define PACKAGE_BUGREPORT "openssh-unix-dev@mindrot.org"
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define _FILE_OFFSET_BITS 64
#define LOGIN_PROGRAM_FALLBACK "/usr/bin/login"
#define _PATH_PASSWD_PROG "/usr/bin/passwd"
#define HAVE_RLIMIT_NPROC
#define WITH_OPENSSL 1
#define HAVE_ATTRIBUTE__NONNULL__ 1
#define HAVE_CRYPT_H 1
#define HAVE_DIRENT_H 1
#define HAVE_ENDIAN_H 1
#define HAVE_ELF_H 1
#define HAVE_FEATURES_H 1
#define HAVE_FCNTL_H 1
#define HAVE_GETOPT_H 1
#define HAVE_GLOB_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_LIMITS_H 1
#define HAVE_LOCALE_H 1
#define HAVE_NETDB_H 1
#define HAVE_PATHS_H 1
#define HAVE_POLL_H 1
#define HAVE_PTY_H 1
#define HAVE_SHADOW_H 1
#define HAVE_STDDEF_H 1
#define HAVE_STDINT_H 1
#define HAVE_STRING_H 1
#define HAVE_STRINGS_H 1
#define HAVE_SYS_BITYPES_H 1
#define HAVE_SYS_CDEFS_H 1
#define HAVE_SYS_DIR_H 1
#define HAVE_SYS_MMAN_H 1
#define HAVE_SYS_POLL_H 1
#define HAVE_SYS_PRCTL_H 1
#define HAVE_SYS_SELECT_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_STROPTS_H 1
#define HAVE_SYS_STATVFS_H 1
#define HAVE_SYS_SYSMACROS_H 1
#define HAVE_SYS_TIME_H 1
#define HAVE_TIME_H 1
#define HAVE_TTYENT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_UTIME_H 1
#define HAVE_UTMP_H 1
#define HAVE_UTMPX_H 1
#define HAVE_LASTLOG_H 1
#define HAVE_SYS_MOUNT_H 1
#define HAVE_SYS_UN_H 1
#define PAM_TTY_KLUDGE 1
#define LOCKED_PASSWD_PREFIX "!"
#define SPT_TYPE SPT_REUSEARGV
#define LINK_OPNOTSUPP_ERRNO EPERM
#define _PATH_BTMP "/var/log/btmp"
#define USE_BTMP 1
#define LINUX_OOM_ADJUST 1
#define HAVE_LINUX_IF_TUN_H 1
#define SSH_TUN_LINUX 1
#define SSH_TUN_COMPAT_AF 1
#define SSH_TUN_PREPEND_AF 1
#define HAVE_LINUX_SECCOMP_H 1
#define HAVE_LINUX_FILTER_H 1
#define HAVE_LINUX_AUDIT_H 1
#define HAVE_PRCTL 1
#define SECCOMP_AUDIT_ARCH AUDIT_ARCH_ARM
#define HAVE_LIBNSL 1
#define HAVE_DIRNAME 1
#define HAVE_LIBGEN_H 1
#define HAVE_BASENAME 1
#define HAVE_LIBZ 1
#define HAVE_UTIMES 1
#define HAVE_LOGIN 1
#define HAVE_LOGOUT 1
#define HAVE_OPENPTY 1
#define HAVE_UPDWTMP 1
#define HAVE_LOGWTMP 1
#define HAVE_STRFTIME 1
#define GLOB_HAS_ALTDIRFUNC 1
#define HAVE_DECL_GLOB_NOMATCH 1
#define BROKEN_ONE_BYTE_DIRENT_D_NAME 1
#define HAVE_PROC_PID 1
#define HAVE_ASPRINTF 1
#define HAVE_BCOPY 1
#define HAVE_CLOCK 1
#define HAVE_DIRFD 1
#define HAVE_ENDGRENT 1
#define HAVE_FCHMOD 1
#define HAVE_FCHOWN 1
#define HAVE_FREEADDRINFO 1
#define HAVE_FSTATFS 1
#define HAVE_FSTATVFS 1
#define HAVE_FUTIMES 1
#define HAVE_GETADDRINFO 1
#define HAVE_GETCWD 1
#define HAVE_GETGROUPLIST 1
#define HAVE_GETNAMEINFO 1
#define HAVE_GETOPT 1
#define HAVE_GETPGID 1
#define HAVE_GETPGRP 1
#define HAVE_GETRLIMIT 1
#define HAVE_GETTTYENT 1
#define HAVE_GLOB 1
#define HAVE_INET_ATON 1
#define HAVE_INET_NTOA 1
#define HAVE_INET_NTOP 1
#define HAVE_INNETGR 1
#define HAVE_MBLEN 1
#define HAVE_MEMMOVE 1
#define HAVE_MKDTEMP 1
#define HAVE_MMAP 1
#define HAVE_POLL 1
#define HAVE_PRCTL 1
#define HAVE_RECVMSG 1
#define HAVE_RRESVPORT_AF 1
#define HAVE_SENDMSG 1
#define HAVE_SETEGID 1
#define HAVE_SETENV 1
#define HAVE_SETEUID 1
#define HAVE_SETGROUPS 1
#define HAVE_SETLINEBUF 1
#define HAVE_SETREGID 1
#define HAVE_SETREUID 1
#define HAVE_SETRLIMIT 1
#define HAVE_SETSID 1
#define HAVE_SETVBUF 1
#define HAVE_SIGACTION 1
#define HAVE_SIGVEC 1
#define HAVE_SNPRINTF 1
#define HAVE_SOCKETPAIR 1
#define HAVE_STATFS 1
#define HAVE_STATVFS 1
#define HAVE_STRDUP 1
#define HAVE_STRERROR 1
#define HAVE_STRNLEN 1
#define HAVE_STRPTIME 1
#define HAVE_STRTOLL 1
#define HAVE_STRTOUL 1
#define HAVE_STRTOULL 1
#define HAVE_SYSCONF 1
#define HAVE_TCGETPGRP 1
#define HAVE_TRUNCATE 1
#define HAVE_UNSETENV 1
#define HAVE_UPDWTMPX 1
#define HAVE_USLEEP 1
#define HAVE_VASPRINTF 1
#define HAVE_VSNPRINTF 1
#define HAVE_WAITPID 1
#define HAVE_ISBLANK 1
#define ENABLE_PKCS11
#define HAVE_GAI_STRERROR 1
#define HAVE_GAI_STRERROR 1
#define HAVE_CONST_GAI_STRERROR_PROTO 1
#define HAVE_NANOSLEEP 1
#define HAVE_CLOCK_GETTIME 1
#define HAVE_STRSEP 1
#define HAVE_TCSENDBREAK 1
#define HAVE_DECL_H_ERRNO 1
#define HAVE_DECL_SHUT_RD 1
#define HAVE_DECL_O_NONBLOCK 1
#define HAVE_DECL_WRITEV 1
#define HAVE_DECL_MAXSYMLINKS 1
#define HAVE_DECL_OFFSETOF 1
#define HAVE_DECL_HOWMANY 1
#define HAVE_DECL_NFDBITS 1
#define HAVE_FD_MASK 1
#define HAVE_SETRESUID 1
#define HAVE_SETRESGID 1
#define HAVE_REALPATH 1
#define HAVE_GETTIMEOFDAY 1
#define HAVE_TIME 1
#define HAVE_ENDUTENT 1
#define HAVE_GETUTENT 1
#define HAVE_GETUTID 1
#define HAVE_GETUTLINE 1
#define HAVE_PUTUTLINE 1
#define HAVE_SETUTENT 1
#define HAVE_UTMPNAME 1
#define HAVE_ENDUTXENT 1
#define HAVE_GETUTXENT 1
#define HAVE_GETUTXID 1
#define HAVE_GETUTXLINE 1
#define HAVE_PUTUTXLINE 1
#define HAVE_SETUTXENT 1
#define HAVE_UTMPXNAME 1
#define HAVE_DAEMON 1
#define HAVE_GETPAGESIZE 1
#define SNPRINTF_CONST const
#define HAVE_SO_PEERCRED 1
#define HAVE_STRICT_MKSTEMP 1
#define HAVE_DECL_AI_NUMERICSERV 1
#define GETPGRP_VOID 1
/* end confdefs.h.  */

/* Override any GCC internal prototype to avoid an error.
   Use char because int might match the return type of a GCC
   builtin and then its argument prototype would still apply.  */
#ifdef __cplusplus
extern "C"
#endif
char RAND_add ();
int
main ()
{
return RAND_add ();
  ;
  return 0;
}
