#----------------------
#Makefile 
#(c) H.Buchmann FHNW 2015
#we are in src 
# TODO change so that all works in work
#see http://www.tldp.org/LDP/lkmpg/2.6/html/x181.html
#----------------------
#KERNEL=/lib/modules/4.14.9-1-ARCH/build/
#KERNEL=${PWD}/../../5-kernel/build
#-------------------- add here your modules
obj-m += simple-module.o 
obj-m += simple-device.o
obj-m += simple-device-1.o
obj-m += simple-device-2.o
obj-m += simple-device-3.o
obj-m += simple-device-4.o
obj-m += simple-device-5.o
obj-m += sysfs.o
obj-m += sysfs-0.o
obj-m += sysfs-1.o
obj-m += sysfs-2.o
obj-m += sysfs-3.o
obj-m += sysfs-device.o




