#------------------------
#Makefile
#(c) H.Buchmann FHNW 2018
#------------------------
TARGET=${PWD}/../tc/bin/arm-linux-gnueabihf
TARGET_ROOT=${PWD}/../target-root
VPATH=../src

CC=${TARGET}-gcc -O2 --sysroot=${TARGET_ROOT}
CXX=${TARGET}-g++ -O2 --sysroot=${TARGET_ROOT}
hello-world-c:  hello-world-c.c

hello-world-cc: hello-world-cc.cc
primes:         primes.cc
