#-----------------------
#Makefile
#(c) H.Buchmann FHNW 2014
#we are in work
#-----------------------
TARGET=../../target-root/
PREFIX=../tc/bin/armv6l-unknown-linux-gnueabihf-
CC=${PREFIX}gcc --sysroot=${TARGET}
CXX=${PREFIX}g++ --sysroot=${TARGET}
VPATH=../src

hello-world-c:		hello-world-c.c
hello-world-cpp:	hello-world-cpp.cc
